// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe0w4Fm4bVYBy3xMWu488bHWuMfIhUGCU',
    appId: '1:553653248027:web:9dcae228a5e465a18658be',
    messagingSenderId: '553653248027',
    projectId: 'campuscuisine',
    authDomain: 'campuscuisine.firebaseapp.com',
    storageBucket: 'campuscuisine.appspot.com',
    measurementId: 'G-NBZ7M6F045',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9qMgpG5GhWqRfPt_gN5n5RUkb9eQRBtk',
    appId: '1:553653248027:android:ee6a7e795d484c678658be',
    messagingSenderId: '553653248027',
    projectId: 'campuscuisine',
    storageBucket: 'campuscuisine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDajlGgxWfyzlBI12HQgajemEydyAl7ghg',
    appId: '1:553653248027:ios:5a9de953118abdb68658be',
    messagingSenderId: '553653248027',
    projectId: 'campuscuisine',
    storageBucket: 'campuscuisine.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDajlGgxWfyzlBI12HQgajemEydyAl7ghg',
    appId: '1:553653248027:ios:3170736ec04e76778658be',
    messagingSenderId: '553653248027',
    projectId: 'campuscuisine',
    storageBucket: 'campuscuisine.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
